#!/usr/bin/env bash
set -euo pipefail

# Resolve repository root from this script's location:
#   <repo>/switching_testing/run_gsum_data_propagation_dump.sh
SCRIPT_PATH="$(readlink -f "$0")"
SWITCHING_DIR="$(dirname "$SCRIPT_PATH")"
REPO_ROOT="$(dirname "$SWITCHING_DIR")"

# Input VCD generated by simulation for the gsum kernel.
VCD_PATH="${REPO_ROOT}/integration-test/gsum/out/sim/HLS_VERIFY/trace.vcd"

# Human-readable text report (event-based global propagation order).
TEXT_PROP_OUT="${REPO_ROOT}/integration-test/gsum/out/comp/all_data_propagation.txt"

# Machine-readable CSV report (event-based global propagation order).
CSV_PROP_OUT="${REPO_ROOT}/integration-test/gsum/out/comp/all_data_propagation.csv"

# Human-readable text report (channel-by-channel sequential order).
TEXT_SEQ_OUT="${REPO_ROOT}/integration-test/gsum/out/comp/all_data_channel_sequential.txt"

# Machine-readable CSV report (channel-by-channel sequential order).
CSV_SEQ_OUT="${REPO_ROOT}/integration-test/gsum/out/comp/all_data_channel_sequential.csv"

# Ensure output directory exists before running the dump.
mkdir -p "$(dirname "$TEXT_PROP_OUT")"

# Build common arguments once so both views use the exact same extraction window.
common_dump_args=(
  python3
  "${SWITCHING_DIR}/dump_data_channels.py"

  # --vcd: input waveform file to parse.
  --vcd "${VCD_PATH}"

  # --window post-reset: only keep events after reset deassertion.
  # This avoids reset/transient initialization noise.
  --window post-reset

  # --show-binary: include binary value alongside decimal per event.
  --show-binary
)

# 1) Event-based report (global time-ordered stream across all channels).
propagation_dump_cmd=(
  "${common_dump_args[@]}"
  # --view propagation: channel index + global time-ordered event stream.
  --view propagation
  # --output: formatted text report path for event-based view.
  --output "${TEXT_PROP_OUT}"
  # --csv: machine-readable event stream in event-based order.
  --csv "${CSV_PROP_OUT}"
)

# 2) Channel-sequential report (one channel at a time, values in order).
sequential_dump_cmd=(
  "${common_dump_args[@]}"
  # --view channel-sequential: channel index + per-channel sequential values.
  --view channel-sequential
  # --output: formatted text report path for channel-sequential view.
  --output "${TEXT_SEQ_OUT}"
  # --csv: machine-readable rows ordered by channel then sequence number.
  --csv "${CSV_SEQ_OUT}"
)

"${propagation_dump_cmd[@]}"
"${sequential_dump_cmd[@]}"

echo "Data extraction dumps generated:"
echo "  propagation text: ${TEXT_PROP_OUT}"
echo "  propagation csv : ${CSV_PROP_OUT}"
echo "  sequential text : ${TEXT_SEQ_OUT}"
echo "  sequential csv  : ${CSV_SEQ_OUT}"
